// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA60f1tyv4tazoScqOFfiyRgbFhLC-6rHU',
    appId: '1:939533047686:web:37e63ffb97a489618bbe07',
    messagingSenderId: '939533047686',
    projectId: 'rightatseven-0521',
    authDomain: 'rightatseven-0521.firebaseapp.com',
    storageBucket: 'rightatseven-0521.firebasestorage.app',
    measurementId: 'G-ZG7CCL4QLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwuvJF9JrBrx9xk46jqnflR7quQrglqxA',
    appId: '1:939533047686:android:1780ce450e54d9d78bbe07',
    messagingSenderId: '939533047686',
    projectId: 'rightatseven-0521',
    storageBucket: 'rightatseven-0521.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbWVHJ3EdWa0ROQQFhdDw80miJGXnEWHI',
    appId: '1:939533047686:ios:008d127ade3c05708bbe07',
    messagingSenderId: '939533047686',
    projectId: 'rightatseven-0521',
    storageBucket: 'rightatseven-0521.firebasestorage.app',
    iosBundleId: 'com.example.rightatseven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbWVHJ3EdWa0ROQQFhdDw80miJGXnEWHI',
    appId: '1:939533047686:ios:008d127ade3c05708bbe07',
    messagingSenderId: '939533047686',
    projectId: 'rightatseven-0521',
    storageBucket: 'rightatseven-0521.firebasestorage.app',
    iosBundleId: 'com.example.rightatseven',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA60f1tyv4tazoScqOFfiyRgbFhLC-6rHU',
    appId: '1:939533047686:web:bd8ed9c326b689508bbe07',
    messagingSenderId: '939533047686',
    projectId: 'rightatseven-0521',
    authDomain: 'rightatseven-0521.firebaseapp.com',
    storageBucket: 'rightatseven-0521.firebasestorage.app',
    measurementId: 'G-KS5RXY59ED',
  );
}
